#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 27 23:08:11 2022

@author: kimsubin
"""

n , k = map(int,input().split())

a = list(map(int,input().split()))
b = list(map(int,input().split()))

a.sort()
b.sort(reverse = True)

for i in range(k):
    
    if a[i]<b[i]:
        
       a[i] , b[i] = b[i], a[i]

print(sum(a))


    
    