#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar 28 12:59:24 2022

@author: kimsubin
"""

n = int(input())

array = list(map(int,input().split()))

m = int(input())
x = list(map(int,input().split()))

for i in x:
    if i in array:
        print("yes",end=" ")
    else:
        print("no",end=" ")
        

# 이분탐색법으로 풀이

def binary_resarch(array,target,start,end):
    while start<=end:
        
        mid = (start+end)//2
        
        if array[mid]==target:
            return mid
        elif array[mid]<target:
            start=mid+1
        else:
           end=mid-1
    return None
 

n = int(input())
array = list(map(int,input().split()))

array.sort()
m = int(input())
x = list(map(int,input().split()))

for i in x:
    result = binary_resarch(array,i,0,n-1)
    
    if result!=None:
        print("yes",end=" ")
    else:
        print("No", end=" ")
        