#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 22 13:23:19 2022

@author: kimsubin
"""

number = int(input())

numbers =[]
for i in range(number):
    numbers.append(int(input()))

numbers.sort()
for i in numbers:
    print(i)
    
    