#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 25 00:35:44 2022

@author: kimsubin
"""

from collections import deque
#import sys
#read = sys.stdin.readline

#dfs
def dfs(v):
    visit1[v] = True
    print(v,end=' ')
    for i in range(1,n+1):
        if not visit1[i] and graph[v][i] == 1:
            dfs(i)
            
#bfs
def bfs(v):
    queue = deque([v])
    visit2[v]= True
    
    while queue:
        v = queue.popleft()
        print(v, end=" ")
        for i in range(1,n+1):
            if not visit2[i] and graph[v][i] ==1:
                queue.append(i)
                visit2[i]=True


#n,m,v = map(int,read().split())
n,m,v = map(int,input().split())

graph=[[0]*(n+1) for _ in range(n+1)] # 왜 n+1이냐면 0번배열은 디폴트로 놔두기 위해서 n번 배열까지 만들기 위해.
visit1 = [False]*(n+1)
visit2 = [False]*(n+1)


for _ in range(m):
    #a,b = map(int,read())
    a,b = map(int,input().split())
    graph[a][b] = graph[b][a] = 1

dfs(v)
print()
bfs(v)