#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 23 13:23:44 2022

@author: kimsubin
"""

n,m = map(int,input().split())

graph = []

for i in range(n):
    graph.append(list(map(int,input())))
    
def dfs(x,y):
    if x<=-1 or x>=n or y<=-1 or y>=n:
        return False
    
    if graph[x][y]==0:
        graph[x][y]=True
        
        dfs(x-1,y)
        dfs(x,y-1)
        dfs(x+1,y)
        dfs(x,y+1)
        return True
    return False

result = 0
for i in range(n):
    for j in range(m):
        if dfs(i,j) ==True:
            result+=1

print(result)